apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: spire-agent
  labels:
    component: spire-agent
    tier: control-plane
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  hostPID: true
  containers:
    - name: spire-agent
      image: gcr.io/spiffe-io/spire-agent:0.10.0
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true

      volumeMounts:
        - name: spire-agent-config
          mountPath: /opt/spire/conf/agent
          readOnly: true

        - name: spire-agent-credentials
          mountPath: /run/spire/credentials
          readOnly: true

        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: false

  volumes:
    - name: spire-agent-credentials
      hostPath:
        path: /tmp/spire-creds
        type: Directory

    - name: spire-agent-config
      hostPath:
        path: /bundle/spire/conf/agent
        type: Directory

    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: DirectoryOrCreate
